name: ci
on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    name: Build + test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:
          - "11.4.2"
          - "11.4.1"
          - "11.3.2"
          - "11.2.1"
          - "11.1.2"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Install Ghidra ${{ matrix.ghidra }}
        uses: antoniovazquezblanco/setup-ghidra@v2.0.3
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ghidra }}
      - name: Build
        run: ./gradlew test buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - uses: actions/upload-artifact@v4
        with:
          name: GhidraSCMP_Ghidra_${{ matrix.ghidra }}
          path: dist/*_GhidraSCMP.zip
          if-no-files-found: 'error'
